### ISSUE TITLE
Cannot read property 'onHardwareBackPress' of undefined

### ISSUE THREAD

**Issue by atteia** [awesomejerry/react-native-back-android#1]
Hello,

I have an error : 

Cannot read property 'onHardwareBackPress' of undefined

hardwareBackPress.js:17

**Comment by awesomejerry** [comment]
Have you wrapped your root component with backAndroid from 'react-native-back-android'?
We use context to get backAndroid handler which has onHardwareBackPress function.

```
...
import backAndroid from 'react-native-back-android';

class App extends React.Component {
  ...
}

export default backAndroid(App);
```

**Comment by atteia** [comment]
I put it in the root as you told

and now I have other error while pressing back button .

Cannot read property 'isOpen' of undefined

and what about handleClose function ? should I create new one ? 
thanks alot for your help !

**Comment by awesomejerry** [comment]
Well, you should define your own logic in the handleHardwareBackPress function. In my case, I use this.state.isOpen to determine if the component should be closed (this.handleClose) when back button pressed.

A full example:

```
import React, { Component } from 'react';
import { View, Text } from 'react-native';
import { hardwareBackPress } from 'react-native-back-android';
import autobind from 'autobind-decorator';

@autobind
class MyStatus extends Component {
  state = {
    isOpen: false,
  };
  handleClose() {
    this.setState({ isOpen: false });
  }
  handleHardwareBackPress() {
    if (this.state.isOpen) {
      this.handleClose();
      return true;
    }
  }
  render() {
    return (
      <View>
        <Text>MyStatus</Text>
      </View>
    );
  }
}

export default hardwareBackPress(MyStatus);
```
