### ISSUE TITLE
React.PropTypes is undefined

### ISSUE THREAD

**Issue by isghanim** [awesomejerry/react-native-back-android#14]
Hi there! I just started using your package and got an error on Android that `React.PropTypes` is undefined in hardwareBackPress.js line 10: `backAndroid: PropTypes.object`. After some googling, it turns out that importing PropTypes from the main React object [is deprecated](https://reactjs.org/blog/2017/04/07/react-v15.5.0.html). I no longer get the error if I import PropTypes like so `import PropTypes from 'prop-types'` in hardwareBackPress.js.

I was wondering if this change could be made in your package?

**Comment by awesomejerry** [comment]
Hello! It's been a while since last time I took a look at this project. I've made a new release. Please check it out!
https://github.com/awesomejerry/react-native-back-android/releases/tag/3.1.1
