### ISSUE TITLE
Cannot perform any work.

### ISSUE THREAD

**Issue by susylPearl** [awesomejerry/react-native-back-android#3]
when i implemented this library nothing happened.

  handleHardwareBackPress() {
    this.navigator.pop();
      /\* don't forget to return true after handling back button press */
      return true;

  }

**Comment by awesomejerry** [comment]
Have you wrapped your root component with backAndroid?

```
...
import backAndroid from 'react-native-back-android';

class App extends React.Component {
  ...
}

export default backAndroid(App);
```
