### ISSUE TITLE
Component that don't have back button handler use it(handler) from previous component

### ISSUE THREAD

**Issue by Mlobaievskyi** [awesomejerry/react-native-back-android#4]
When I press the back button on component that don't have a handler (don't need to perform any back button action on it) it use handler from previouse component even if it unmounted.

**Comment by awesomejerry** [comment]
Can you provide a simple example? The handler of unmounted component should be removed when componentWillUnmount occurs.

**Comment by Mlobaievskyi** [comment]
Example: You have two views first one has backButton handler (asking to exit the app) and second just go back to first view `navigator.pop(0)`. When you go from first one to second with `navigator.push()` back button will start to listen second view and after you go back (navigator.pop(0)) you will still listen to second view handler.

**Comment by awesomejerry** [comment]
Have fixed the bug and release a new version. Please try it.

**Comment by Mlobaievskyi** [comment]
Yes, it works well now. Thank you!
