### ISSUE TITLE
Hardcoded peerDependencies?

### ISSUE THREAD

**Issue by mikelambert** [awesomejerry/react-native-back-android#9]
I am using this without issue on 0.39. Is there a reason for the hardcoded dependencies, versus using a semver or "*"?
  "peerDependencies": {
    "react": "15.0.2",
    "react-native": "0.26.2"
  },

**Comment by awesomejerry** [comment]
That's just for my testing to work. Will use the wildcard cuz it's actually relatively independent from react-native
